name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: my-project
  REGION: asia-south1
  REPOSITORY: Python-WebApp-HelloWorld
  SERVICE: hello-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/123456789/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@my-project.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/webapp:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/webapp:${{ github.sha }}

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/webapp:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
